import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { Client } from "https://deno.land/x/postgres@v0.17.0/mod.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// Process tables in smaller chunks to avoid CPU timeout
const TABLES_PER_CHUNK = 10;
const MAX_ROWS_PER_BATCH = 300;
const BATCH_SIZE_ROWS = 200;

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  let pgClient: Client | null = null;

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) throw new Error("Missing authorization header");

    const supabaseClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_ANON_KEY") ?? "",
      { global: { headers: { Authorization: authHeader } } }
    );

    const { data: { user }, error: userError } = await supabaseClient.auth.getUser();
    if (userError || !user) throw new Error("Unauthorized");

    const { 
      instanceId, 
      databaseName, 
      format = 'sql', 
      includeData = true,
      chunkIndex = 0,
      getMetadataOnly = false  // New: just get table list and chunk count
    } = await req.json();
    
    if (!instanceId) throw new Error("instanceId is required");

    const { data: instance, error: instanceError } = await supabaseClient
      .from("postgres_instances")
      .select("*")
      .eq("id", instanceId)
      .single();

    if (instanceError || !instance) throw new Error("Instance not found");

    const targetDb = databaseName || instance.database;
    
    pgClient = new Client({
      hostname: instance.host,
      port: instance.port,
      user: instance.username,
      password: instance.password,
      database: targetDb,
      tls: instance.ssl_enabled ? { enabled: true, enforce: false } : undefined,
      connection: { attempts: 1 },
    });

    await pgClient.connect();
    console.log(`Connected to ${instance.host}:${instance.port}/${targetDb}`);

    // Get all table names
    const tablesResult = await pgClient.queryObject<{ table_name: string }>(`
      SELECT table_name FROM information_schema.tables
      WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
      ORDER BY table_name
    `);

    const allTables = tablesResult.rows.map(t => t.table_name);
    const totalTables = allTables.length;
    const totalChunks = Math.ceil(totalTables / TABLES_PER_CHUNK);

    // If just getting metadata, return early
    if (getMetadataOnly) {
      await pgClient.end();
      return new Response(
        JSON.stringify({
          success: true,
          metadata: {
            totalTables,
            totalChunks,
            tablesPerChunk: TABLES_PER_CHUNK,
            tables: allTables,
            database: targetDb
          }
        }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    console.log(`Processing chunk ${chunkIndex + 1}/${totalChunks} (${TABLES_PER_CHUNK} tables per chunk)`);

    const startTime = Date.now();
    const sqlParts: string[] = [];

    // Determine which tables to process in this chunk
    const startIdx = chunkIndex * TABLES_PER_CHUNK;
    const endIdx = Math.min(startIdx + TABLES_PER_CHUNK, totalTables);
    const tablesToProcess = allTables.slice(startIdx, endIdx);

    console.log(`Processing ${tablesToProcess.length} tables: ${tablesToProcess.join(', ')}`);

    // Add header only on first chunk
    if (chunkIndex === 0) {
      sqlParts.push(`--
-- PostgreSQL database dump
-- Generated by Lovable Backup System
-- Host: ${instance.host}:${instance.port}
-- Database: ${targetDb}
-- Date: ${new Date().toISOString()}
-- Total Tables: ${totalTables}
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET row_security = off;
SET session_replication_role = 'replica';

`);
    }

    let totalRows = 0;

    for (const tableName of tablesToProcess) {
      try {
        // Get columns
        const columnsResult = await pgClient.queryObject<{
          column_name: string;
          data_type: string;
          is_nullable: string;
          column_default: string | null;
          character_maximum_length: number | null;
        }>(`
          SELECT column_name, data_type, is_nullable, column_default, character_maximum_length
          FROM information_schema.columns
          WHERE table_schema = 'public' AND table_name = $1
          ORDER BY ordinal_position
        `, [tableName]);

        const columns = columnsResult.rows;
        if (columns.length === 0) continue;

        // Get primary key
        const pkResult = await pgClient.queryObject<{ column_name: string }>(`
          SELECT kcu.column_name FROM information_schema.table_constraints tc
          JOIN information_schema.key_column_usage kcu ON tc.constraint_name = kcu.constraint_name
          WHERE tc.table_schema = 'public' AND tc.table_name = $1 AND tc.constraint_type = 'PRIMARY KEY'
        `, [tableName]);

        // Build CREATE TABLE
        const columnDefs = columns.map(col => {
          let typeDef = col.data_type.toUpperCase();
          if (col.character_maximum_length) typeDef = `${typeDef}(${col.character_maximum_length})`;
          if (col.is_nullable === 'NO') typeDef += ' NOT NULL';
          if (col.column_default) typeDef += ` DEFAULT ${col.column_default}`;
          return `  "${col.column_name}" ${typeDef}`;
        });

        if (pkResult.rows.length > 0) {
          const pkCols = pkResult.rows.map(r => `"${r.column_name}"`).join(', ');
          columnDefs.push(`  PRIMARY KEY (${pkCols})`);
        }

        sqlParts.push(`-- Table: ${tableName}\nDROP TABLE IF EXISTS public."${tableName}" CASCADE;\n`);
        sqlParts.push(`CREATE TABLE public."${tableName}" (\n${columnDefs.join(',\n')}\n);\n\n`);

        // Insert data if requested
        if (includeData) {
          const countResult = await pgClient.queryObject<{ cnt: number }>(
            `SELECT COUNT(*)::int as cnt FROM public."${tableName}"`
          );
          const rowCount = countResult.rows[0]?.cnt || 0;
          
          if (rowCount > 0) {
            const columnNames = columns.map(c => `"${c.column_name}"`).join(', ');
            
            // Fetch ALL data, but in batches
            let offset = 0;
            let tableRows = 0;
            
            sqlParts.push(`-- Data for ${tableName} (${rowCount} rows)\n`);
            
            while (offset < rowCount) {
              const fetchLimit = Math.min(BATCH_SIZE_ROWS, rowCount - offset);
              const dataResult = await pgClient.queryObject(
                `SELECT * FROM public."${tableName}" LIMIT ${fetchLimit} OFFSET ${offset}`
              );
              const rows = dataResult.rows as Record<string, unknown>[];
              
              if (rows.length === 0) break;
              
              // Generate INSERT statements in smaller batches
              for (let i = 0; i < rows.length; i += 50) {
                const batch = rows.slice(i, i + 50);
                const valuesArray = batch.map(row => {
                  const vals = columns.map(col => escapeSqlValue(row[col.column_name])).join(', ');
                  return `(${vals})`;
                });
                sqlParts.push(`INSERT INTO public."${tableName}" (${columnNames}) VALUES\n${valuesArray.join(',\n')};\n`);
              }
              
              tableRows += rows.length;
              offset += fetchLimit;
            }
            
            totalRows += tableRows;
            sqlParts.push('\n');
          }
        }
      } catch (tableError) {
        console.error(`Error processing table ${tableName}:`, tableError);
        sqlParts.push(`-- Error processing table ${tableName}: ${tableError instanceof Error ? tableError.message : 'Unknown error'}\n\n`);
      }
    }

    // Determine if this is the last chunk
    const isLastChunk = chunkIndex >= totalChunks - 1;

    // Add footer only on last chunk
    if (isLastChunk) {
      sqlParts.push(`
SET session_replication_role = 'origin';

--
-- PostgreSQL database dump complete
-- Chunk ${chunkIndex + 1}/${totalChunks} (final)
--
`);
    } else {
      sqlParts.push(`-- End of chunk ${chunkIndex + 1}/${totalChunks}\n`);
    }

    await pgClient.end();

    const sqlContent = sqlParts.join('');
    const chunkSize = new TextEncoder().encode(sqlContent).length;
    const duration = Date.now() - startTime;
    
    console.log(`Chunk ${chunkIndex + 1}/${totalChunks}: ${tablesToProcess.length} tables, ${totalRows} rows, ${(chunkSize / 1024).toFixed(2)} KB in ${duration}ms`);

    return new Response(
      JSON.stringify({
        success: true,
        content: sqlContent,
        stats: {
          tables: tablesToProcess.length,
          rows: totalRows,
          size: chunkSize,
          duration,
          database: targetDb,
          format: 'sql'
        },
        chunk: {
          index: chunkIndex,
          total: totalChunks,
          isLast: isLastChunk,
          tablesProcessed: tablesToProcess
        }
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );

  } catch (error: unknown) {
    const errorMessage = error instanceof Error ? error.message : "Unknown error";
    console.error("Backup error:", errorMessage);
    
    if (pgClient) {
      try { await pgClient.end(); } catch { /* ignore */ }
    }

    return new Response(
      JSON.stringify({ success: false, message: errorMessage }),
      { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});

function escapeSqlValue(value: unknown): string {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
  if (typeof value === 'number') return String(value);
  if (value instanceof Date) return `'${value.toISOString()}'`;
  if (typeof value === 'object') return `'${JSON.stringify(value).replace(/'/g, "''")}'`;
  return `'${String(value).replace(/'/g, "''")}'`;
}
