import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { Client } from "https://deno.land/x/postgres@v0.17.0/mod.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface TableInfo {
  table_name: string;
  table_schema: string;
}

interface ColumnInfo {
  column_name: string;
  data_type: string;
  is_nullable: string;
  column_default: string | null;
  character_maximum_length: number | null;
  numeric_precision: number | null;
  numeric_scale: number | null;
}

interface ConstraintInfo {
  constraint_name: string;
  constraint_type: string;
  column_name: string;
  foreign_table: string | null;
  foreign_column: string | null;
}

// Escape SQL string values
function escapeSqlValue(value: unknown): string {
  if (value === null || value === undefined) {
    return 'NULL';
  }
  if (typeof value === 'boolean') {
    return value ? 'TRUE' : 'FALSE';
  }
  if (typeof value === 'number') {
    return String(value);
  }
  if (value instanceof Date) {
    return `'${value.toISOString()}'`;
  }
  if (typeof value === 'object') {
    return `'${JSON.stringify(value).replace(/'/g, "''")}'`;
  }
  return `'${String(value).replace(/'/g, "''")}'`;
}

// Map PostgreSQL types to SQL type definitions
function getColumnDefinition(col: ColumnInfo): string {
  let typeDef = col.data_type.toUpperCase();
  
  if (col.character_maximum_length) {
    typeDef = `${typeDef}(${col.character_maximum_length})`;
  } else if (col.numeric_precision && col.data_type === 'numeric') {
    typeDef = `NUMERIC(${col.numeric_precision}${col.numeric_scale ? `, ${col.numeric_scale}` : ''})`;
  }
  
  if (col.is_nullable === 'NO') {
    typeDef += ' NOT NULL';
  }
  
  if (col.column_default) {
    typeDef += ` DEFAULT ${col.column_default}`;
  }
  
  return typeDef;
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  const encoder = new TextEncoder();
  let pgClient: Client | null = null;

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      throw new Error("Missing authorization header");
    }

    const supabaseClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_ANON_KEY") ?? "",
      { global: { headers: { Authorization: authHeader } } }
    );

    const { data: { user }, error: userError } = await supabaseClient.auth.getUser();
    if (userError || !user) {
      throw new Error("Unauthorized");
    }

    const { instanceId, databaseName, format = 'sql', includeData = true } = await req.json();
    
    if (!instanceId) {
      throw new Error("instanceId is required");
    }

    // Fetch instance details
    const { data: instance, error: instanceError } = await supabaseClient
      .from("postgres_instances")
      .select("*")
      .eq("id", instanceId)
      .single();

    if (instanceError || !instance) {
      throw new Error("Instance not found");
    }

    console.log(`Connecting to PostgreSQL: ${instance.host}:${instance.port}/${databaseName || instance.database}`);

    // Connect to PostgreSQL
    pgClient = new Client({
      hostname: instance.host,
      port: instance.port,
      user: instance.username,
      password: instance.password,
      database: databaseName || instance.database,
      tls: instance.ssl_enabled ? { enabled: true, enforce: false } : undefined,
    });

    await pgClient.connect();
    console.log("Connected to PostgreSQL");

    const startTime = Date.now();
    const targetDb = databaseName || instance.database;
    
    // Build the SQL dump
    let sqlContent = '';
    
    // Header
    sqlContent += `--\n`;
    sqlContent += `-- PostgreSQL database dump\n`;
    sqlContent += `-- Generated by Lovable Backup System\n`;
    sqlContent += `--\n`;
    sqlContent += `-- Host: ${instance.host}:${instance.port}\n`;
    sqlContent += `-- Database: ${targetDb}\n`;
    sqlContent += `-- Date: ${new Date().toISOString()}\n`;
    sqlContent += `--\n\n`;
    
    sqlContent += `SET statement_timeout = 0;\n`;
    sqlContent += `SET lock_timeout = 0;\n`;
    sqlContent += `SET idle_in_transaction_session_timeout = 0;\n`;
    sqlContent += `SET client_encoding = 'UTF8';\n`;
    sqlContent += `SET standard_conforming_strings = on;\n`;
    sqlContent += `SELECT pg_catalog.set_config('search_path', '', false);\n`;
    sqlContent += `SET check_function_bodies = false;\n`;
    sqlContent += `SET xmloption = content;\n`;
    sqlContent += `SET client_min_messages = warning;\n`;
    sqlContent += `SET row_security = off;\n\n`;

    // Get all tables in public schema
    const tablesResult = await pgClient.queryObject<TableInfo>(`
      SELECT table_name, table_schema
      FROM information_schema.tables
      WHERE table_schema = 'public'
        AND table_type = 'BASE TABLE'
      ORDER BY table_name
    `);

    const tables = tablesResult.rows;
    console.log(`Found ${tables.length} tables`);

    let totalRows = 0;

    for (const table of tables) {
      const tableName = table.table_name;
      console.log(`Processing table: ${tableName}`);

      // Get columns
      const columnsResult = await pgClient.queryObject<ColumnInfo>(`
        SELECT 
          column_name, 
          data_type, 
          is_nullable, 
          column_default,
          character_maximum_length,
          numeric_precision,
          numeric_scale
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = $1
        ORDER BY ordinal_position
      `, [tableName]);

      const columns = columnsResult.rows;

      // Get constraints (primary keys, foreign keys)
      const constraintsResult = await pgClient.queryObject<ConstraintInfo>(`
        SELECT 
          tc.constraint_name,
          tc.constraint_type,
          kcu.column_name,
          ccu.table_name AS foreign_table,
          ccu.column_name AS foreign_column
        FROM information_schema.table_constraints tc
        JOIN information_schema.key_column_usage kcu 
          ON tc.constraint_name = kcu.constraint_name
          AND tc.table_schema = kcu.table_schema
        LEFT JOIN information_schema.constraint_column_usage ccu 
          ON tc.constraint_name = ccu.constraint_name
          AND tc.table_schema = ccu.table_schema
        WHERE tc.table_schema = 'public' AND tc.table_name = $1
      `, [tableName]);

      const constraints = constraintsResult.rows;

      // Generate CREATE TABLE
      sqlContent += `--\n-- Table: ${tableName}\n--\n\n`;
      sqlContent += `DROP TABLE IF EXISTS public."${tableName}" CASCADE;\n\n`;
      sqlContent += `CREATE TABLE public."${tableName}" (\n`;

      const columnDefs = columns.map(col => 
        `  "${col.column_name}" ${getColumnDefinition(col)}`
      );

      // Add primary key constraint
      const pkConstraint = constraints.find(c => c.constraint_type === 'PRIMARY KEY');
      if (pkConstraint) {
        const pkColumns = constraints
          .filter(c => c.constraint_name === pkConstraint.constraint_name)
          .map(c => `"${c.column_name}"`)
          .join(', ');
        columnDefs.push(`  PRIMARY KEY (${pkColumns})`);
      }

      sqlContent += columnDefs.join(',\n');
      sqlContent += `\n);\n\n`;

      // Add foreign key constraints
      const fkConstraints = constraints.filter(c => c.constraint_type === 'FOREIGN KEY');
      const processedFks = new Set<string>();
      
      for (const fk of fkConstraints) {
        if (!processedFks.has(fk.constraint_name)) {
          processedFks.add(fk.constraint_name);
          sqlContent += `ALTER TABLE public."${tableName}" ADD CONSTRAINT "${fk.constraint_name}" `;
          sqlContent += `FOREIGN KEY ("${fk.column_name}") REFERENCES public."${fk.foreign_table}"("${fk.foreign_column}");\n`;
        }
      }

      if (fkConstraints.length > 0) {
        sqlContent += '\n';
      }

      // Generate INSERT statements if includeData is true
      if (includeData) {
        const dataResult = await pgClient.queryObject(`SELECT * FROM public."${tableName}"`);
        const rows = dataResult.rows as Record<string, unknown>[];

        if (rows.length > 0) {
          sqlContent += `--\n-- Data for table: ${tableName}\n--\n\n`;
          
          const columnNames = columns.map(c => `"${c.column_name}"`).join(', ');
          
          for (const row of rows) {
            const values = columns.map(col => escapeSqlValue(row[col.column_name])).join(', ');
            sqlContent += `INSERT INTO public."${tableName}" (${columnNames}) VALUES (${values});\n`;
            totalRows++;
          }
          
          sqlContent += '\n';
        }
      }
    }

    // Get sequences
    const sequencesResult = await pgClient.queryObject<{ sequence_name: string }>(`
      SELECT sequence_name
      FROM information_schema.sequences
      WHERE sequence_schema = 'public'
    `);

    if (sequencesResult.rows.length > 0) {
      sqlContent += `--\n-- Sequences\n--\n\n`;
      
      for (const seq of sequencesResult.rows) {
        const seqValueResult = await pgClient.queryObject<{ last_value: number }>(`
          SELECT last_value FROM public."${seq.sequence_name}"
        `);
        
        if (seqValueResult.rows.length > 0) {
          sqlContent += `SELECT pg_catalog.setval('public."${seq.sequence_name}"', ${seqValueResult.rows[0].last_value}, true);\n`;
        }
      }
      sqlContent += '\n';
    }

    // Get indexes (non-primary key)
    const indexesResult = await pgClient.queryObject<{ indexdef: string }>(`
      SELECT indexdef
      FROM pg_indexes
      WHERE schemaname = 'public'
        AND indexname NOT IN (
          SELECT constraint_name 
          FROM information_schema.table_constraints 
          WHERE constraint_type = 'PRIMARY KEY'
        )
    `);

    if (indexesResult.rows.length > 0) {
      sqlContent += `--\n-- Indexes\n--\n\n`;
      for (const idx of indexesResult.rows) {
        sqlContent += `${idx.indexdef};\n`;
      }
      sqlContent += '\n';
    }

    // Footer
    sqlContent += `--\n`;
    sqlContent += `-- PostgreSQL database dump complete\n`;
    sqlContent += `-- Tables: ${tables.length}\n`;
    sqlContent += `-- Rows: ${totalRows}\n`;
    sqlContent += `-- Generated in: ${Date.now() - startTime}ms\n`;
    sqlContent += `--\n`;

    await pgClient.end();

    const backupSize = encoder.encode(sqlContent).length;
    console.log(`Backup generated: ${tables.length} tables, ${totalRows} rows, ${(backupSize / 1024).toFixed(2)} KB`);

    return new Response(
      JSON.stringify({
        success: true,
        content: sqlContent,
        stats: {
          tables: tables.length,
          rows: totalRows,
          size: backupSize,
          duration: Date.now() - startTime,
          database: targetDb,
          format: 'sql'
        }
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );

  } catch (error: unknown) {
    const errorMessage = error instanceof Error ? error.message : "Unknown error";
    console.error("Backup error:", errorMessage);
    
    if (pgClient) {
      try { await pgClient.end(); } catch { /* ignore */ }
    }

    return new Response(
      JSON.stringify({ success: false, message: errorMessage }),
      { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
