import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { Client } from "https://deno.land/x/postgres@v0.17.0/mod.ts";
import { requireOperatorOrAdmin } from "../_shared/auth.ts";
import { decrypt } from "../_shared/crypto.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// Chunk configuration - user defined limits
const MAX_ROWS_PER_CHUNK = 5000; // 5.000 rows max per chunk
const BATCH_SIZE_ROWS = 500; // 500 rows per batch
const MAX_STRING_LENGTH = 2000000; // 2MB max string length
const TABLE_TIMEOUT_MS = 90000; // 90 seconds timeout per table

interface ChunkCursor {
  tableIndex: number;    // Current table index in the list
  rowOffset: number;     // Row offset within current table
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  let pgClient: Client | null = null;

  try {
    const authHeader = req.headers.get("Authorization");
    
    // Verify user has operator or admin role
    await requireOperatorOrAdmin(
      authHeader,
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_ANON_KEY") ?? ""
    );

    const supabaseClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_ANON_KEY") ?? "",
      { global: { headers: { Authorization: authHeader! } } }
    );

    const { 
      instanceId, 
      databaseName, 
      format = 'sql', 
      includeData = true,
      getMetadataOnly = false,
      // Incremental cursor - where to resume from
      cursor = null as ChunkCursor | null,
    } = await req.json();
    
    if (!instanceId) throw new Error("instanceId is required");

    const { data: instance, error: instanceError } = await supabaseClient
      .from("postgres_instances")
      .select("*")
      .eq("id", instanceId)
      .single();

    if (instanceError || !instance) throw new Error("Instance not found");

    const targetDb = databaseName || instance.database;
    
    // Decrypt password if encrypted
    const decryptedPassword = await decrypt(instance.password);
    
    pgClient = new Client({
      hostname: instance.host,
      port: instance.port,
      user: instance.username,
      password: decryptedPassword,
      database: targetDb,
      tls: instance.ssl_enabled ? { enabled: true, enforce: false } : undefined,
      connection: { attempts: 1 },
    });

    await pgClient.connect();
    console.log(`Connected to ${instance.host}:${instance.port}/${targetDb}`);

    // Get all table names
    const tablesResult = await pgClient.queryObject<{ table_name: string }>(`
      SELECT table_name FROM information_schema.tables
      WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
      ORDER BY table_name
    `);

    const allTables = tablesResult.rows.map(t => t.table_name);
    const totalTables = allTables.length;

    // Get row counts for all tables to estimate total chunks
    const tableCounts: { [key: string]: number } = {};
    let totalRows = 0;
    
    for (const tableName of allTables) {
      const countResult = await pgClient.queryObject<{ cnt: number }>(
        `SELECT COUNT(*)::int as cnt FROM public."${tableName}"`
      );
      const count = countResult.rows[0]?.cnt || 0;
      tableCounts[tableName] = count;
      totalRows += count;
    }
    
    // Estimate total chunks based on rows
    const estimatedChunks = Math.max(1, Math.ceil(totalRows / MAX_ROWS_PER_CHUNK));

    // If just getting metadata, return early
    if (getMetadataOnly) {
      await pgClient.end();
      return new Response(
        JSON.stringify({
          success: true,
          metadata: {
            totalTables,
            totalRows,
            estimatedChunks,
            maxRowsPerChunk: MAX_ROWS_PER_CHUNK,
            tables: allTables.map(t => ({ name: t, rows: tableCounts[t] })),
            database: targetDb
          }
        }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Initialize cursor
    const currentCursor: ChunkCursor = cursor || { tableIndex: 0, rowOffset: 0 };
    const isFirstChunk = currentCursor.tableIndex === 0 && currentCursor.rowOffset === 0;
    
    console.log(`Processing from table ${currentCursor.tableIndex} (${allTables[currentCursor.tableIndex] || 'END'}), row offset ${currentCursor.rowOffset}`);

    const startTime = Date.now();
    const sqlParts: string[] = [];
    let rowsProcessedInChunk = 0;
    let tablesProcessedInChunk = 0;
    let lastProcessedTableName = '';
    
    // Next cursor position (will be updated as we process)
    let nextCursor: ChunkCursor | null = null;
    let hasMoreData = false;

    // Add header only on first chunk
    if (isFirstChunk) {
      sqlParts.push(`--
-- PostgreSQL database dump
-- Generated by Lovable Backup System
-- Host: ${instance.host}:${instance.port}
-- Database: ${targetDb}
-- Date: ${new Date().toISOString()}
-- Total Tables: ${totalTables}
-- Total Rows: ${totalRows}
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET row_security = off;
SET session_replication_role = 'replica';

`);
    }

    // Process tables starting from cursor position
    for (let tableIdx = currentCursor.tableIndex; tableIdx < totalTables; tableIdx++) {
      const tableName = allTables[tableIdx];
      lastProcessedTableName = tableName;
      const tableRowCount = tableCounts[tableName];
      const tableStartTime = Date.now();
      
      // Starting row offset for this table
      const startRowOffset = (tableIdx === currentCursor.tableIndex) ? currentCursor.rowOffset : 0;
      
      // Check if we need to output table structure (only if starting from row 0)
      const isNewTable = startRowOffset === 0;
      
      try {
        // Get columns
        const columnsResult = await pgClient.queryObject<{
          column_name: string;
          data_type: string;
          is_nullable: string;
          column_default: string | null;
          character_maximum_length: number | null;
        }>(`
          SELECT column_name, data_type, is_nullable, column_default, character_maximum_length
          FROM information_schema.columns
          WHERE table_schema = 'public' AND table_name = $1
          ORDER BY ordinal_position
        `, [tableName]);

        const columns = columnsResult.rows;
        if (columns.length === 0) continue;

        // Get primary key for ordering
        const pkResult = await pgClient.queryObject<{ column_name: string }>(`
          SELECT kcu.column_name FROM information_schema.table_constraints tc
          JOIN information_schema.key_column_usage kcu ON tc.constraint_name = kcu.constraint_name
          WHERE tc.table_schema = 'public' AND tc.table_name = $1 AND tc.constraint_type = 'PRIMARY KEY'
        `, [tableName]);

        // Build CREATE TABLE only if new table
        if (isNewTable) {
          const columnDefs = columns.map(col => {
            let typeDef = col.data_type.toUpperCase();
            if (col.character_maximum_length) typeDef = `${typeDef}(${col.character_maximum_length})`;
            if (col.is_nullable === 'NO') typeDef += ' NOT NULL';
            if (col.column_default) typeDef += ` DEFAULT ${col.column_default}`;
            return `  "${col.column_name}" ${typeDef}`;
          });

          if (pkResult.rows.length > 0) {
            const pkCols = pkResult.rows.map(r => `"${r.column_name}"`).join(', ');
            columnDefs.push(`  PRIMARY KEY (${pkCols})`);
          }

          sqlParts.push(`\n-- Table: ${tableName}\nDROP TABLE IF EXISTS public."${tableName}" CASCADE;\n`);
          sqlParts.push(`CREATE TABLE public."${tableName}" (\n${columnDefs.join(',\n')}\n);\n\n`);
          
          if (tableRowCount > 0) {
            sqlParts.push(`-- Data for ${tableName} (${tableRowCount} rows total)\n`);
          }
          
          tablesProcessedInChunk++;
        }
        // NOTE: Removed continuation comment - it was causing corruption when inserted between chunks

        // Insert data if requested
        if (includeData && tableRowCount > 0) {
          const columnNames = columns.map(c => `"${c.column_name}"`).join(', ');
          const selectCols = columns.map(c => `"${c.column_name}"::text`).join(', ');
          const orderClause = pkResult.rows.length > 0 
            ? `ORDER BY ${pkResult.rows.map(r => `"${r.column_name}"`).join(', ')}`
            : '';
          
          let currentRowOffset = startRowOffset;
          
          while (currentRowOffset < tableRowCount) {
            // Check if we've hit the chunk limit
            if (rowsProcessedInChunk >= MAX_ROWS_PER_CHUNK) {
              // Save cursor for next chunk
              nextCursor = { tableIndex: tableIdx, rowOffset: currentRowOffset };
              hasMoreData = true;
              console.log(`Chunk limit reached. Next cursor: table ${tableIdx}, row ${currentRowOffset}`);
              break;
            }
            
            // Check timeout
            const elapsedMs = Date.now() - tableStartTime;
            if (elapsedMs > TABLE_TIMEOUT_MS) {
              // Save cursor for next chunk due to timeout
              nextCursor = { tableIndex: tableIdx, rowOffset: currentRowOffset };
              hasMoreData = true;
              console.log(`Table timeout. Next cursor: table ${tableIdx}, row ${currentRowOffset}`);
              // NOTE: Removed inline comment - it was causing SQL corruption
              break;
            }
            
            // Calculate how many rows to fetch
            const remainingInChunk = MAX_ROWS_PER_CHUNK - rowsProcessedInChunk;
            const remainingInTable = tableRowCount - currentRowOffset;
            const fetchLimit = Math.min(BATCH_SIZE_ROWS, remainingInChunk, remainingInTable);
            
            try {
              const dataResult = await pgClient.queryArray(
                `SELECT ${selectCols} FROM public."${tableName}" ${orderClause} LIMIT ${fetchLimit} OFFSET ${currentRowOffset}`
              );
              
              if (dataResult.rows.length === 0) break;
              
              // Generate INSERT statements - CRITICAL: Build complete statement atomically
              for (const row of dataResult.rows) {
                // Build values array safely
                const valuesParts: string[] = [];
                for (let idx = 0; idx < row.length; idx++) {
                  const escapedVal = escapeSqlValueFromText(row[idx], columns[idx].data_type);
                  // Validate that escaped value doesn't contain unescaped newlines
                  if (escapedVal.includes('\n') && !escapedVal.includes('\\n')) {
                    console.error(`Warning: Unescaped newline in value for column ${columns[idx].column_name}`);
                  }
                  valuesParts.push(escapedVal);
                }
                const vals = valuesParts.join(', ');
                
                // Build complete INSERT as a single atomic string
                // CRITICAL: Must be on a single line to prevent chunk boundary corruption
                const insertStmt = `INSERT INTO public."${tableName}" (${columnNames}) VALUES (${vals});`;
                
                // Validate statement structure before adding
                if (!insertStmt.includes(' VALUES (') || !insertStmt.endsWith(');')) {
                  console.error(`Malformed INSERT detected for table ${tableName}, row offset ${currentRowOffset}`);
                  sqlParts.push(`-- SKIPPED malformed row at offset ${currentRowOffset}\n`);
                  continue;
                }
                
                sqlParts.push(insertStmt + '\n');
              }
              
              rowsProcessedInChunk += dataResult.rows.length;
              currentRowOffset += dataResult.rows.length;
            } catch (queryError) {
              console.error(`Query error for ${tableName} at offset ${currentRowOffset}:`, queryError);
              sqlParts.push(`-- Error fetching data at offset ${currentRowOffset}: ${queryError instanceof Error ? queryError.message : 'Unknown'}\n`);
              break;
            }
          }
          
          // If we completed this table, add newline
          if (!hasMoreData && currentRowOffset >= tableRowCount) {
            sqlParts.push('\n');
          }
        }
        
        // Break outer loop if we need to continue in next chunk
        if (hasMoreData) break;
        
      } catch (tableError) {
        console.error(`Error processing table ${tableName}:`, tableError);
        sqlParts.push(`-- Error processing table ${tableName}: ${tableError instanceof Error ? tableError.message : 'Unknown error'}\n\n`);
      }
    }

    // Determine if this is the last chunk
    const isLastChunk = !hasMoreData;

    // Add footer only on last chunk
    if (isLastChunk) {
      sqlParts.push(`\n\nSET session_replication_role = 'origin';

--
-- PostgreSQL database dump complete
-- All ${totalRows} rows from ${totalTables} tables included
--
`);
    } else {
      // Add clear chunk delimiter to prevent data corruption on append
      sqlParts.push(`\n-- === END OF CHUNK ${currentCursor.tableIndex}_${currentCursor.rowOffset} ===\n\n`);
    }

    await pgClient.end();

    const sqlContent = sqlParts.join('');
    const contentBytes = new TextEncoder().encode(sqlContent);
    const chunkSize = contentBytes.length;
    const duration = Date.now() - startTime;
    
    // Calculate SHA256 checksum of the chunk content
    const hashBuffer = await crypto.subtle.digest("SHA-256", contentBytes);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    const chunkChecksum = hashArray.map(b => b.toString(16).padStart(2, "0")).join("");
    
    console.log(`Chunk complete: ${tablesProcessedInChunk} new tables, ${rowsProcessedInChunk} rows, ${(chunkSize / 1024).toFixed(2)} KB in ${duration}ms. Checksum: ${chunkChecksum.substring(0, 16)}...`);

    return new Response(
      JSON.stringify({
        success: true,
        content: sqlContent,
        stats: {
          tablesInChunk: tablesProcessedInChunk,
          rowsInChunk: rowsProcessedInChunk,
          size: chunkSize,
          duration,
          database: targetDb,
          format: 'sql',
          totalTables,
          totalRows,
          currentTableName: lastProcessedTableName,
          checksum: chunkChecksum,
        },
        pagination: {
          isFirstChunk,
          isLastChunk,
          hasMoreData,
          nextCursor,
          currentCursor,
        }
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );

  } catch (error: unknown) {
    const errorMessage = error instanceof Error ? error.message : "Unknown error";
    console.error("Backup error:", errorMessage);
    
    if (pgClient) {
      try { await pgClient.end(); } catch { /* ignore */ }
    }

    return new Response(
      JSON.stringify({ success: false, message: errorMessage }),
      { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});

// Escape SQL value from text representation (avoids date parsing issues)
function escapeSqlValueFromText(value: unknown, dataType: string): string {
  // CRITICAL: Always return a valid SQL value, never empty string
  if (value === null || value === undefined) return 'NULL';
  
  const strValue = String(value);
  
  // Handle empty strings - always return valid SQL
  if (strValue === '' || strValue === 'null' || strValue === 'undefined') {
    // For text types, return empty string; for others, return NULL
    if (dataType.includes('char') || dataType === 'text' || dataType === 'name') {
      return "''";
    }
    return 'NULL';
  }
  
  // Handle boolean
  if (dataType === 'boolean') {
    const lower = strValue.toLowerCase();
    if (lower === 't' || lower === 'true' || strValue === '1') return 'TRUE';
    if (lower === 'f' || lower === 'false' || strValue === '0') return 'FALSE';
    return 'NULL'; // Invalid boolean -> NULL
  }
  
  // Handle numeric types - validate and return as-is or NULL
  if (dataType.includes('int') || dataType.includes('numeric') || dataType.includes('decimal') || 
      dataType === 'real' || dataType === 'double precision' || dataType === 'money') {
    // Validate it's a valid number
    const cleanValue = strValue.replace(/,/g, '.').trim();
    if (cleanValue === '' || isNaN(Number(cleanValue.replace(/[^\d.-]/g, '')))) {
      return 'NULL';
    }
    return cleanValue;
  }
  
  // Handle bytea/binary
  if (dataType === 'bytea') {
    if (strValue.length > 20000) {
      return `'[BINARY_DATA_TRUNCATED_${strValue.length}_CHARS]'`;
    }
    // Escape properly
    return escapeStringValue(strValue);
  }
  
  // Handle all other types as strings
  return escapeStringValue(strValue);
}

// Helper function to properly escape string values for SQL
function escapeStringValue(value: string): string {
  let finalValue = value;
  
  // Truncate very long strings
  if (finalValue.length > MAX_STRING_LENGTH) {
    finalValue = finalValue.substring(0, MAX_STRING_LENGTH) + '...[TRUNCATED]';
  }
  
  // CRITICAL: Remove all control characters and problematic bytes FIRST
  // Remove null bytes
  finalValue = finalValue.replace(/\x00/g, '');
  // Remove other control characters (except tab which might be intentional)
  finalValue = finalValue.replace(/[\x01-\x08\x0B\x0C\x0E-\x1F\x7F]/g, '');
  
  // CRITICAL: Escape backslashes FIRST (before other escapes)
  finalValue = finalValue.replace(/\\/g, '\\\\');
  
  // Escape single quotes by doubling them
  finalValue = finalValue.replace(/'/g, "''");
  
  // CRITICAL: Convert actual newlines to escaped representation
  // This prevents line breaks that would corrupt the SQL statement
  finalValue = finalValue.replace(/\r\n/g, ' ');  // Replace CRLF with space
  finalValue = finalValue.replace(/\n/g, ' ');    // Replace LF with space  
  finalValue = finalValue.replace(/\r/g, ' ');    // Replace CR with space
  finalValue = finalValue.replace(/\t/g, ' ');    // Replace tabs with space
  
  // Remove any remaining problematic characters
  finalValue = finalValue.replace(/[\u0000-\u001F]/g, '');
  
  // Collapse multiple spaces into single space
  finalValue = finalValue.replace(/  +/g, ' ');
  
  // Trim whitespace
  finalValue = finalValue.trim();
  
  // If empty after all processing, return empty string
  if (finalValue === '') {
    return "''";
  }
  
  return `'${finalValue}'`;
}
